// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Components.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Components.Streams;

public interface _SinkOperations
{
    void finalizeTransport(boolean now, Source theSource, Components.TransportProfileHolder tranPro, Ice.Current __current)
        throws GenericError;

    void modifyTransport(Components.TransportProfile tpformodify, Ice.Current __current)
        throws GenericError;

    void releaseTransport(Ice.Current __current);

    void startStream(PreviouAction previous, byte[] theMarker, StreamProfile sp, Components.TransportProfile tp, Ice.Current __current)
        throws GenericError;

    void finishStream(byte[] markerForFinish, Ice.Current __current)
        throws GenericError;

    void abortStream(byte[] markerForAbort, Ice.Current __current)
        throws GenericError;
}
