// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Components.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Components.Streams;

public interface _StreamPortContextOperationsNC
{
    Components.TransportProfile getTransportProfile();

    StreamProfile getStreamProfile();

    void abort();

    void setEnableNewBuffer(boolean enableNewBuffer);

    boolean getEnableNewBuffer();

    void setBufferTimeout(long timeout);

    long getBufferTimeout();

    StreamBuffer getBuffer(long minimumSize, boolean _wait)
        throws GenericError;
}
