// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Components.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Components.Streams;

public final class SourcePrxHelper extends Ice.ObjectPrxHelperBase implements SourcePrx
{
    private static final String __abortStream_name = "abortStream";

    public byte[] abortStream()
    {
        return abortStream(null, false);
    }

    public byte[] abortStream(java.util.Map<String, String> __ctx)
    {
        return abortStream(__ctx, true);
    }

    private byte[] abortStream(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "abortStream", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("abortStream");
                    __delBase = __getDelegate(false);
                    _SourceDel __del = (_SourceDel)__delBase;
                    return __del.abortStream(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_abortStream()
    {
        return begin_abortStream(null, false, null);
    }

    public Ice.AsyncResult begin_abortStream(java.util.Map<String, String> __ctx)
    {
        return begin_abortStream(__ctx, true, null);
    }

    public Ice.AsyncResult begin_abortStream(Ice.Callback __cb)
    {
        return begin_abortStream(null, false, __cb);
    }

    public Ice.AsyncResult begin_abortStream(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_abortStream(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_abortStream(Callback_Source_abortStream __cb)
    {
        return begin_abortStream(null, false, __cb);
    }

    public Ice.AsyncResult begin_abortStream(java.util.Map<String, String> __ctx, Callback_Source_abortStream __cb)
    {
        return begin_abortStream(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_abortStream(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__abortStream_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __abortStream_name, __cb);
        try
        {
            __result.__prepare(__abortStream_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public byte[] end_abortStream(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __abortStream_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            byte[] __ret;
            __ret = MarkerHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __modifyTransport_name = "modifyTransport";

    public void modifyTransport(Components.TransportProfile theProfile)
        throws GenericError
    {
        modifyTransport(theProfile, null, false);
    }

    public void modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx)
        throws GenericError
    {
        modifyTransport(theProfile, __ctx, true);
    }

    private void modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws GenericError
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "modifyTransport", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("modifyTransport");
                    __delBase = __getDelegate(false);
                    _SourceDel __del = (_SourceDel)__delBase;
                    __del.modifyTransport(theProfile, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile)
    {
        return begin_modifyTransport(theProfile, null, false, null);
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx)
    {
        return begin_modifyTransport(theProfile, __ctx, true, null);
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, Ice.Callback __cb)
    {
        return begin_modifyTransport(theProfile, null, false, __cb);
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_modifyTransport(theProfile, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, Callback_Source_modifyTransport __cb)
    {
        return begin_modifyTransport(theProfile, null, false, __cb);
    }

    public Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx, Callback_Source_modifyTransport __cb)
    {
        return begin_modifyTransport(theProfile, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_modifyTransport(Components.TransportProfile theProfile, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__modifyTransport_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __modifyTransport_name, __cb);
        try
        {
            __result.__prepare(__modifyTransport_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            theProfile.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_modifyTransport(Ice.AsyncResult __result)
        throws GenericError
    {
        Ice.AsyncResult.__check(__result, this, __modifyTransport_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(GenericError __ex)
                {
                    throw __ex;
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            __result.__readEmptyParams();
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static SourcePrx checkedCast(Ice.ObjectPrx __obj)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SourcePrx)
            {
                __d = (SourcePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    SourcePrxHelper __h = new SourcePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SourcePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SourcePrx)
            {
                __d = (SourcePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    SourcePrxHelper __h = new SourcePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SourcePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    SourcePrxHelper __h = new SourcePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SourcePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    SourcePrxHelper __h = new SourcePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SourcePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SourcePrx)
            {
                __d = (SourcePrx)__obj;
            }
            else
            {
                SourcePrxHelper __h = new SourcePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static SourcePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SourcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            SourcePrxHelper __h = new SourcePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Components::Streams::Source",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _SourceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _SourceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, SourcePrx v)
    {
        __os.writeProxy(v);
    }

    public static SourcePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            SourcePrxHelper result = new SourcePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
