// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Components.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Components.Streams;

public final class StreamPortsPrxHelper extends Ice.ObjectPrxHelperBase implements StreamPortsPrx
{
    public static StreamPortsPrx checkedCast(Ice.ObjectPrx __obj)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof StreamPortsPrx)
            {
                __d = (StreamPortsPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static StreamPortsPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof StreamPortsPrx)
            {
                __d = (StreamPortsPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static StreamPortsPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static StreamPortsPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static StreamPortsPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof StreamPortsPrx)
            {
                __d = (StreamPortsPrx)__obj;
            }
            else
            {
                StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static StreamPortsPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        StreamPortsPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            StreamPortsPrxHelper __h = new StreamPortsPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Components::Streams::StreamPorts",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _StreamPortsDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _StreamPortsDelD();
    }

    public static void __write(IceInternal.BasicStream __os, StreamPortsPrx v)
    {
        __os.writeProxy(v);
    }

    public static StreamPortsPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            StreamPortsPrxHelper result = new StreamPortsPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
