// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Components.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Components.Streams;

public interface StreamBuffer
{
    void setStreamInfo(byte[] info4s);

    byte[] getStreamInfo();

    void setTransportInfo(byte[] info4t);

    byte[] getTransportInfo();

    boolean getLast();

    void setLast(boolean last);

    void setHasData(boolean hasData);

    boolean getHasData();

    void release();

    void take();

    public static final long serialVersionUID = -324317159118648526L;
}
